title: numgeo-ACT
description: Automatic Calibration Tool (ACT) based on the fem-program numgeo (Machaček & Staubach, [www.numgeo.de])

source: ./docs
includes: ./docs/_includes

theme: just-the-docs

url: https://j-machacek.github.io/test/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
