title: numgeo-ACT
description: Automatic Calibration Tool (ACT) for advanced constitutive soil models

source: ./docs

theme: just-the-docs

url: https://j-machacek.github.io/test/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
